// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etokhrazfflokvyssdep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0b2tocmF6ZmZsb2t2eXNzZGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1OTg3MDUsImV4cCI6MjA4NDE3NDcwNX0.C4FCKq-ncQzDp6K5d1dXdBY04-GP_PzelWNx1Gg1x8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});